version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: anonymous-board-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: board_db
      MYSQL_USER: board_user
      MYSQL_PASSWORD: board_pass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d

volumes:
  db_data:
